import fs from 'node:fs/promises';
import { Presentation, PresentationFile } from '@oai/artifact-tool';
const OUT='C:/Users/USUARIO/Downloads/codex/pedidosTPO/Presentacion_Pedidos_PO_Negocio.pptx';
const DIR='C:/Users/USUARIO/Downloads/codex/pedidosTPO/.tmp/pedidos_po_presentation/business-output';
const C={ink:'#101828',muted:'#475467',light:'#F2F4F7',line:'#D0D5DD',blue:'#3D8DFF',pale:'#EAF5FB',mint:'#D9F8E8',amber:'#FFF2CC',white:'#FFFFFF',dark:'#0B1220'};
async function save(path,b){await fs.writeFile(path,new Uint8Array(await b.arrayBuffer()));}
function box(s,x,y,w,h,fill=C.white,line=C.line){return s.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill:line,width:1}});}
function txt(s,v,x,y,w,h,z=20,o={}){const a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}});a.text=v;a.text.style={fontSize:z,fontFace:'Helvetica Neue',color:o.color||C.ink,bold:o.bold||false,alignment:o.align||'left',verticalAlignment:'top',autoFit:'shrinkText',insets:{left:0,right:0,top:0,bottom:0}};return a;}
function rule(s,x,y,w,fill=C.line,h=1){return s.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill,width:0}});}
function arr(s,x,y,w,h=18,fill=C.blue){return s.shapes.add({geometry:'rightArrow',position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill,width:0}});}
function node(s,label,detail,x,y,w,h,fill=C.light){box(s,x,y,w,h,fill);rule(s,x,y,6,C.blue,6);txt(s,label,x+18,y+18,w-34,30,22,{bold:true});txt(s,detail,x+18,y+54,w-34,h-66,17,{color:C.muted});}
function slide(p){const s=p.slides.add();s.background.fill=C.white;return s;}
function header(s,sec,n){txt(s,sec.toUpperCase(),56,28,450,20,13,{bold:true,color:C.muted});txt(s,String(n).padStart(2,'0'),1180,28,44,20,13,{align:'right',color:C.muted});rule(s,56,57,1168);}
function title(s,h,sub,n,sec){header(s,sec,n);txt(s,h,56,84,1120,64,38,{bold:true});txt(s,sub,56,158,1100,44,20,{color:C.muted});}
function notes(s,v){s.speakerNotes.textFrame.setText(`[Sources]\n${v}`);s.speakerNotes.setVisible(true);}
function s1(p){const s=slide(p);rule(s,56,56,7,554,C.blue,7);txt(s,'PEDIDOS PO',86,55,350,24,18,{bold:true,color:C.muted});txt(s,'Convertir pedidos\ndispersos en una\nentrada clara.',86,175,780,250,62,{bold:true});txt(s,'Una aplicación sencilla para estandarizar la recepción de pedidos de sofás.',88,480,850,36,24,{color:C.muted});txt(s,'Presentación de producto y soporte tecnológico',88,544,600,28,19,{color:C.blue,bold:true});box(s,920,172,250,300,C.pale,C.pale);txt(s,'PEDIDO',950,207,150,28,20,{bold:true,color:C.muted});txt(s,'claro',950,250,170,55,42,{bold:true});rule(s,950,326,180);txt(s,'Cliente\nArtículos\nCantidades\nObservaciones',950,350,160,100,18,{color:C.muted});notes(s,'Contexto de negocio aportado por el solicitante; README.md.');}
function s2(p){const s=slide(p);title(s,'El punto de partida: pedidos que llegan de muchas formas','El departamento de pedidos debe interpretar y transcribir información antes de poder introducirla en el ERP.',2,'El problema');const a=[['Email','Información poco\nestructurada'],['WhatsApp','Mensajes, fotos\ny aclaraciones'],['Albarán manual','Datos escritos\na mano'],['Otros formatos','Información\ndistribuida']];a.forEach((v,i)=>{const x=56+i*278;box(s,x,270,230,160,i===2?C.amber:C.light);txt(s,v[0],x+18,296,180,28,22,{bold:true});txt(s,v[1],x+18,338,180,55,17,{color:C.muted});if(i<3)arr(s,x+236,337,36,15,C.muted);});rule(s,56,492,1168);txt(s,'Consecuencia: la transcripción hacia el ERP se convierte en un cuello de botella operativo.',56,532,1080,38,25,{bold:true});notes(s,'Contexto de negocio aportado por el solicitante.');}
function s3(p){const s=slide(p);title(s,'La aplicación estandariza la recepción sin complicar al representante','El representante crea un pedido guiado; el departamento recibe una estructura única, completa y legible.',3,'La solución');arr(s,320,345,72);arr(s,704,345,72);node(s,'Representante','Selecciona cliente, modelo, artículos y cantidades',56,270,250,160,C.pale);node(s,'Pedidos PO','Recoge los datos con un formato único',405,270,285,160,C.mint);node(s,'Departamento de pedidos','Consulta una orden clara y lista para procesar',790,270,360,160,C.light);txt(s,'El valor no está en “digitalizar por digitalizar”: está en reducir la interpretación manual antes de operar.',56,535,1100,36,23,{bold:true});notes(s,'Contexto de negocio aportado por el solicitante; app/pedidos/new-order-form.js; app/pedidos/page.js.');}
function s4(p){const s=slide(p);title(s,'El flujo mejora la lectura; el ERP sigue siendo el sistema de registro','Hoy no hay integración automática: la aplicación prepara la información para que su carga al ERP sea más rápida y fiable.',4,'Alcance');const a=[['Entrada actual','Email · WhatsApp\nalbarán manual'],['Pedido estructurado','Cliente + artículos\n+ cantidades + notas'],['Revisión operativa','Información clara\ny trazable'],['ERP','Introducción manual\npero agilizada']];a.forEach((v,i)=>{const x=56+i*292;box(s,x,280,244,160,i===1?C.mint:(i===3?C.amber:C.light));txt(s,v[0],x+18,305,208,28,21,{bold:true});txt(s,v[1],x+18,347,205,56,17,{color:C.muted});if(i<3)arr(s,x+250,346,36,15);});txt(s,'No sustituye al ERP ni exporta pedidos automáticamente; estandariza y facilita el paso anterior.',56,535,1080,38,23,{bold:true});notes(s,'Alcance de producto aportado por el solicitante; README.md.');}
function s5(p){const s=slide(p);title(s,'Qué recibe el equipo de pedidos','Cada pedido concentra las piezas que hoy deben localizarse, interpretar y contrastar entre distintos canales.',5,'Resultado');const a=[['Cliente','Código y nombre comercial'],['Modelo y artículos','Catálogo vigente y selección'],['Cantidades','Líneas de pedido claras'],['Notas','Observaciones en un único lugar'],['Estado','Pendiente, confirmado o en fabricación']];a.forEach((v,i)=>{const x=56+(i%3)*386,y=260+Math.floor(i/3)*145;box(s,x,y,350,108,i===0?C.pale:C.light);txt(s,v[0],x+18,y+18,310,26,20,{bold:true});txt(s,v[1],x+18,y+52,310,26,17,{color:C.muted});});txt(s,'Resultado operativo: menos tiempo interpretando el pedido y más tiempo registrándolo correctamente en el ERP.',56,570,1100,34,22,{bold:true});notes(s,'app/pedidos/page.js; app/pedidos/new-order-form.js; app/pedidos/actions.js.');}
function s6(p){const s=slide(p);title(s,'El catálogo de producto parte de un Excel controlado','El administrador importa la tarifa, revisa una versión en borrador y decide cuándo queda disponible para crear pedidos.',6,'Catálogo');const a=[['Excel','Tarifa y clientes'],['Importación','Validación del archivo'],['Borrador','Versión revisable'],['Publicado','Disponible en pedidos']];a.forEach((v,i)=>{const x=56+i*292;box(s,x,285,240,150,i===3?C.mint:C.light);txt(s,v[0],x+18,312,190,28,22,{bold:true});txt(s,v[1],x+18,355,190,32,17,{color:C.muted});if(i<3)arr(s,x+246,350,38,15);});txt(s,'Así, los representantes trabajan siempre con una tarifa publicada y se evita que una carga nueva altere el servicio en curso.',56,535,1100,40,22,{bold:true});notes(s,'README.md; app/api/catalog/import/route.js; app/catalog/actions.js; lib/catalog.js.');}
function s7(p){const s=slide(p);title(s,'Tecnología: servicios gestionados para centrarnos en el proceso','La solución combina una aplicación web con servicios en la nube ya preparados para autenticación, datos y despliegue.',7,'Tecnología');const a=[['Aplicación web','Next.js\nLa interfaz que usan los equipos'],['Usuarios y datos','Supabase\nAutenticación y base de datos'],['Despliegue','Vercel\nPublicación de la aplicación'],['Catálogo','Excel\nFuente de tarifas y clientes']];a.forEach((v,i)=>{const x=56+i*292;box(s,x,270,250,185,i===1?C.pale:C.light);txt(s,v[0],x+18,298,210,28,22,{bold:true});txt(s,v[1],x+18,345,210,58,18,{color:C.muted});});txt(s,'El objetivo del stack es práctico: fiabilidad y velocidad de evolución sin gestionar infraestructura propia.',56,545,1100,34,22,{bold:true});notes(s,'README.md; package.json; lib/supabase/*.js.');}
function s8(p){const s=slide(p);title(s,'Cómo se ha desarrollado y entregado','El proyecto combina desarrollo asistido por IA, control de versiones y un despliegue automatizado desde la rama principal.',8,'Desarrollo');const a=[['IA','Apoyo al desarrollo\ny aceleración de iteraciones'],['GitHub','Historial, control de versiones\ny revisión de cambios'],['Vercel','Despliegue de la rama\nmain a producción']];a.forEach((v,i)=>{const x=56+i*390;box(s,x,285,350,175,i===2?C.pale:C.light);txt(s,v[0],x+18,312,300,28,23,{bold:true});txt(s,v[1],x+18,358,300,54,18,{color:C.muted});if(i<2)arr(s,x+356,356,28,15);});txt(s,'Este flujo permite mejorar la aplicación de forma controlada, manteniendo un historial claro de los cambios.',56,545,1100,34,22,{bold:true});notes(s,'README.md; package.json; contexto de desarrollo asistido por IA aportado por el solicitante.');}
function s9(p){const s=slide(p);rule(s,56,56,7,554,C.blue,7);txt(s,'PRÓXIMOS PASOS',86,55,350,24,18,{bold:true,color:C.muted});txt(s,'Primero: adopción y\nmedición del impacto.\nDespués: integración.',86,180,900,220,57,{bold:true});txt(s,'1. Conseguir que los representantes centralicen sus pedidos\n2. Medir la reducción de tiempo de transcripción y errores\n3. Evaluar una futura integración con el ERP con datos reales',88,465,950,104,23,{color:C.muted});notes(s,'Recomendación de evolución basada en el alcance aportado por el solicitante.');}
async function main(){await fs.mkdir(DIR,{recursive:true});const p=Presentation.create({slideSize:{width:1280,height:720}});[s1,s2,s3,s4,s5,s6,s7,s8,s9].forEach(f=>f(p));for(let i=0;i<p.slides.items.length;i++)await save(`${DIR}/slide-${String(i+1).padStart(2,'0')}.png`,await p.export({slide:p.slides.items[i],format:'png',scale:1}));const d=await PresentationFile.exportPptx(p);await d.save(OUT);}
main().catch(e=>{console.error(e);process.exitCode=1;});
